# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YWEyZmMxNjE4N2VhZjlhYTYwZGRkMDQwNDg1OGFjZmM5ZmIzYjUzNDRmNzBlODFlMjJkNzFiY2ZiNmFhNzBiYzg3N2ZmZTVkZDYwZjBhY2E5NTAzYjI0ODdhZGVhYWNiNWFkNjY5N2YyYTI4OWM5NjBhZjBlMDIxN2RhNTQxZWQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
